_base_:
- ../../dataset/etth1.yml
_custom_imports_:
- SeqSNN.network
- SeqSNN.dataset
- SeqSNN.runner

runner:
  type: ts
  task: regression
  optimizer: Adam
  lr: 0.001
  weight_decay: 0.0
  loss_fn: mse
  metrics: [r2, rrse]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 30
  batch_size: 32
  aggregate: True

network:
  type: TCN
  position_embedding: False
  emb_type: learn
  kernel_size: 64
  num_levels: 3
  channel: 16
  dilation: 2
  dropout: 0.

runtime: 
  seed: 42
  output_dir: ./output/tcnEtth1