_base_:
- ../../dataset/etth1.yml
_custom_imports_:
- SeqSNN.network
- SeqSNN.dataset
- SeqSNN.runner

data:
  is_vsts: True

runner:
  type: vsts
  task: regression
  optimizer: Adam
  lr: 0.001
  weight_decay: 0.0
  loss_fn: mse
  metrics: [r2, rse, mae, mse, corr]
  observe: loss
  lower_is_better: True
  max_epoches: 1000
  early_stop: 30
  batch_size: 32
  aggregate: True
  valid_variates: 7

network:
  type: iSpikformer
  dim: 256
  d_ff: 512
  depths: 2
  num_steps: 4
  heads: 8
  use_cluster: False
  n_cluster: 3
  d_model: 64

runtime:
  seed: 39
  output_dir: ./output/ispikformerEtth1